import setuptools

setuptools.setup(name='shapeletpy',
      version='0.1',
      description='Time series classification Using Shapelets',
      url='https://github.com/rohitvincent/shapeletpy',
      author='Rohit Vincent',
      author_email='rohit.vincent@ucdconnect.ie',
      license='MIT',
      packages=setuptools.find_packages(),
	  install_requires=[
          'markdown',
		  'collections',
		  'itertools',
		  'operator',
		  'pickle',
		  'random',
		  'threading',
		  'time',
		  'sklearn',
		  'matplotlib',
		  'numpy',
		  'pandas',
		  'progressbar',
		  'seaborn',
		  'saxpy',
		  'scipy'],
      zip_safe=False)